ju/illustration/urls.py
from django.contrib import admin
from django.urls import path,include
from illustration import views
app_name='illustration'
urlpatterns = [
    path('home/',views.home,name='home'),
    path('contact/',views.contact,name='contact'),
    path('index/', views.index,name='index'),
    path('community_detail/', views.community_detail, name='community_detail'),
    path('register/', views.user_register,name='register'),
    path('login/',views.user_login,name='login'),
    path('userinfo/',views.user_info,name='userinfo'),
    path('settings/',views.user_settings,name='settings'),
    path('reset_pwd/',views.reset_pwd,name='reset_pwd'),
    path('logout/',views.user_logout,name='logout'),
    path('bizcircle_community/',views.bizcircle_community),
    path('station_community/',views.station_community),
    path('search_community/<str:kind>', views.search_community,name='search_community'),
    # path('show_collect/illus/search_community/<str:kind>', views.search_community),
    path('his_price/',views.his_price,name='his_price'),
    path('his_detail/',views.his_detail,name='his_detail'),
    path('community_info/',views.community_info),
    path('community_hisprice/',views.community_hisprice,name='community_hisprice'),
    path('community_hisdetail/',views.community_hisdetail,name='community_hisdetail'),
    path('district_hisprice/',views.district_hisprice,name='district_hisprice'),
    path('news/',views.news,name='news'),
    path('collect/',views.collect,name='collect'),
    path('show_collect/',views.show_collect,name='show_collect'),
    path('invest_ass/',views.invest_ass,name='invest_ass'),
    path('price_predict/',views.price_predict,name='price_predict'),
    path('buy_or_rent/',views.buy_or_rent,name='buy_or_rent'),
]

ju/ju/urls.py
from django.contrib import admin
from django.urls import path,include
from illustration.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('illus/', include('illustration.urls', namespace='illustration')),
]

ju/illustration/forms.py
from django import forms
from illustration.models import UserProfile,UserCollect

class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class RegisterForm(forms.Form):
    username = forms.CharField(required=True,min_length=4)
    password = forms.CharField(required=True,min_length=6)
    repeat = forms.CharField(required=True,min_length=6)

# 用于个人中心修改个人信息
class UserInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['username','email','mobile']

class UserCollectForm(forms.ModelForm):
    class Meta:
        model = UserCollect
        fields = ['user','community_id']

# 重置密码
class ResetPwdForm(forms.Form):
    oldpassword = forms.CharField(required=True)
    newpassword = forms.CharField(required=True, min_length=6)
    repeatpassword = forms.CharField(required=True, min_length=6)

ju/illustration/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from . import  models
from django.db.models import Avg,Count
from django.shortcuts import render,redirect
from django.conf import settings
import json
from django.forms.models import model_to_dict
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from django.contrib import auth
from django.core.serializers import serialize
from django.core.serializers.json import  DjangoJSONEncoder
from django.contrib.auth.hashers import make_password
from django.db.models import F
from django.contrib import messages
import requests
import datetime


from django.shortcuts import render
# Django自带的用户认证、登录与注销方法
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db.models import Q
from django.views.generic.base import  View
from . import  models
from .models import UserProfile,UserCollect
from .forms import LoginForm, RegisterForm, UserInfoForm, ResetPwdForm,UserCollectForm

# pure pagination开源库进行分页
from django.shortcuts import render_to_response

from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def home(request):
        # 数据库中数据按照时间降序排列，此处取出前四条数据
        newslist = models.newsFlash.objects.all()[:4]
        return render(request, 'home.html',{"newslist":newslist})
def contact(request):
    return render(request, 'contact.html')
def index(request):
    return render(request,'index.html')
def search_community(request,kind):
    return render(request, 'search_community.html',{'kind':kind})
def user_register(request):
    if request.method == "GET":
        return render(request,'register.html')
    elif request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get('username','')
            if UserProfile.objects.filter(username=user_name):
                return render(
                    request,"register.html",{
                        "register_form": register_form,"msg": "用户已存在"})
            pass_word = request.POST.get('password',' ')
            repeat_psw = request.POST.get('repeat',' ')
            if pass_word == repeat_psw:
                user_profile = UserProfile()
                user_profile.username = user_name
                # 密码不可明文存储，通过make_password方法加密
                user_profile.password = make_password(pass_word)
                user_profile.save()
                return render(request,'login.html')
            else:
                return render(
                    request,"register.html",{
                        "register_form": register_form,"msg": "两次输入密码不一致"})
        else:
            return render(request,'register.html',{"msg": "用户名或密码不合法"})


# 用户登录
def bizcircle_community(request):
    input = request.POST.get('input')
    data = models.Community.objects.filter(bizcircle=input).values()
    data = json.dumps(list(data), cls=DjangoJSONEncoder, ensure_ascii=False)
    return HttpResponse(data)

def station_community(request):
    station = request.POST.get('station')
    data = models.Community.objects.filter(taglist__contains=station).values()
    data = json.dumps(list(data), cls=DjangoJSONEncoder, ensure_ascii=False)
    return HttpResponse(data)

def user_login(request):
    if request.method == "GET":
        return render(request,'login.html')
    elif request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get('username','')
            pass_word = request.POST.get('password',' ')
            # 成功返回user对象,失败返回null
            user = authenticate(username=user_name,password=pass_word)
            if user is not None:
                login(request,user)
                newslist = models.newsFlash.objects.all()[:4]
                return render(request,'home.html',{"newslist": newslist})
            else:
                return render(request,'login.html',{"msg": "用户名或密码错误!"})
        else:
            return render(request,'login.html',{"msg": "用户名或密码缺失"})

# 用户退出
def user_logout(request):
    logout(request)
    newslist = models.newsFlash.objects.all()[:4]
    return render(request,'home.html',{"newslist": newslist})

def user_settings(request):
    if request.method == "GET":
        return render(request,"settings.html",{})

def user_info(request):
    if request.method == "POST":
        # return render(request,'settings.html',{ })
        # 不像用户咨询是一个新的。需要指明instance 不然会变成新增用户
        user_info_form = UserInfoForm(request.POST,instance=request.user)
        # return render(request,'settings.html')
        if user_info_form.is_valid():
            user_info_form.email = request.POST.get("email",'')
            user_info_form.mobile = request.POST.get("mobile",'')
            user_info_form.save()
            return render(request,'settings.html',{})

def reset_pwd(request):
    if request.method == "POST":
        reset_form = ResetPwdForm(request.POST)
        # return render(request,'settings.html')
        user = request.user
        if reset_form.is_valid():
            oldpwd = request.POST.get("oldpassword")
            newpwd = request.POST.get("newpassword","")
            repwd = request.POST.get("repeatpassword","")
            if user.check_password(oldpwd):
                # 如果两次密码不相等，返回错误信息
                if newpwd != repwd:
                    return render(request,'settings.html',{"msg": "两次输入密码不一致"})
                user.password = make_password(repwd)
                user.save()
                logout(request)
                return render(request,'login.html',{})
            else:
                return render(request,'settings.html',{"msg": "原始密码不符，请重新输入"})
        # 验证失败说明密码位数不够。
        else:
            return render(request,"settings.html",{
                "modiypwd_form": reset_form,"msg": "密码输入格式有误"})

def community_detail(request):

    community_title=request.POST.get('community')
    community=models.Community.objects.filter(title=community_title)
    if len(community)==0:
        messages.warning(request,'抱歉，查找失败')
        return render(request,'index.html')
    community = community[0]
    collect_status = 0
    if request.user.is_authenticated:
        id = community.id
        is_collect = models.UserCollect.objects.filter(user=request.user.username,community_id=int(id))
        if len(is_collect) == 0:
            collect_status = 0
        else:
            collect_status = 1
    address="上海市"+community.district+community_title
    parameters1 = {'address': address, 'key': 'f14f3c4d3e03c58b2cb53fdacb49ecb7'}
    base1 = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base1, parameters1)
    answer = response.json()
    lng=answer['geocodes'][0]['location'].split(',')[0]
    lat=answer['geocodes'][0]['location'].split(',')[1]
    base2='http://restapi.amap.com/v3/place/around'
    parameters2={'location':answer['geocodes'][0]['location'], 'keywords':'医院','type':'090000','radius':1000,'key': 'f14f3c4d3e03c58b2cb53fdacb49ecb7'}
    count = requests.get(base2, parameters2).json()['count']
    return render(request,'community_detail.html',{'community':community,'lng':lng,'lat':lat,'count':count,'collect_status':collect_status})

def his_price(request):
    unitprice_infos=[]
    dateList=['2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08', '2017-09','2017-10', '2017-11', '2017-12',
              '2018-01', '2018-02', '2018-03']
    for date in dateList:
        unitprice_infos.append(models.Sellinfo.objects.filter(dealdate__contains=date).exclude(unitprice='下载APP查看成交>').aggregate(avgprice=Avg('unitprice')))
    return render(request,'his_price.html',{'unitprice_infos':unitprice_infos})
def his_detail(request):
    return render(request,'his_detail.html')
def community_info(request):
    return render(request,'community_info.html')
def community_hisprice(request):
    community=request.POST.get('community')
    data=models.Sellinfo.objects.filter(community=community).exclude(unitprice='下载APP查看成交>').values('dealdate','unitprice').order_by('dealdate')
    data = json.dumps(list(data), cls=DjangoJSONEncoder)
    return HttpResponse(data)

def community_hisdetail(request):
    community = request.POST.get('community')
    data=models.Houseinfo.objects.filter(community=community).values('housetype').annotate(Count('housetype'))
    data = json.dumps(list(data), cls=DjangoJSONEncoder,ensure_ascii=False)
    return HttpResponse(data)
def district_hisprice(request):
    district = request.POST.get('district')
    data = models.Sellinfo.objects.filter(district=district).exclude(unitprice='下载APP查看成交>').values('dealdate','unitprice').order_by('dealdate')
    data = json.dumps(list(data), cls=DjangoJSONEncoder, ensure_ascii=False)
    return HttpResponse(data)

# 从数据库获取新闻资讯返回
def news(request):

    newslist = models.newsFlash.objects.all().order_by('id')

    # 对新闻进行分页
    try:
        page = request.GET.get('page',1)
    except PageNotAnInteger:
        page = 1
    p = Paginator(newslist,6,request=request)

    news = p.page(page)
    return render(request, 'news.html',{"newslist":news})

def collect(request):
     if request.method == "POST":
         # 默认值为0 防止程序崩盘
         id = request.POST.get('community_id',0)

         # 收藏与已收藏取消收藏
         # 判断用户是否登录:即使没登录会有一个匿名的user
         if not request.user.is_authenticated:
             # 未登录时返回json提示未登录，跳转到登录页面在ajax中实现
             # return HttpResponse('{"status":0, "msg":"用户未登录"}',content_type='application/json')
             data = json.dumps({"status":0, "msg": "用户未登录"},cls=DjangoJSONEncoder)
             return HttpResponse(data)

ju/illustration/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<header id="site-header"class="navbar-fixed-top">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <figure id="site-logo">
                    <a href="index.html"><img src="{% static "assets/images/logo.png"%}" alt="Logo" style="height: 65px"></a><!--logo要改！！！！！！！！！-->
                </figure>
            </div>
            <div class="col-md-6 col-sm-8">
                <nav id="site-nav" class="nav navbar-default">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'illustration:home' %}">首页</a></li>
                        <li><a href="{% url 'illustration:index' %}">房源信息</a>  <!--链接要改！！！！！！！！！！！！！--></li>
{#                        <li><a href="single-property.html">房价预测</a></li>#}
                        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">预测投资 <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'illustration:price_predict'%}">房价预测</a></li>
                                    <li><a href="{% url 'illustration:invest_ass'%}">投资助手</a></li>
                                    <li><a href="{% url 'illustration:buy_or_rent'%}">买or租</a></li>
                                </ul>
                        </li>
                        <li><a href="{% url 'illustration:news'%}">最新资讯</a></li>
                        <li>
                            <a href="{% url 'illustration:contact' %}">联系我们</a>
                        </li>

                        {% if request.user.is_authenticated %}
                            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">{{ request.user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'illustration:show_collect'%}">我的</a></li>
                                    <li><a href="{% url 'illustration:settings'%}">设置</a></li>
                                    <li><a href="{% url 'illustration:logout'%}">退出</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">用户 <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'illustration:login'%}">登录</a></li>
                                    <li><a href="{% url 'illustration:register'%}">注册</a></li>
                                </ul>
                            </li>
                        {% endif %}


                    </ul>
                </nav>
            </div>
            <div class="col-md-3 col-sm-4">
                <div class="contact-in-header clearfix">
                    <i class="fa fa-mobile"></i>
                    <span>
                        Call Us Now
                        <br>
                    <strong>111 222 333 444</strong>
                    </span>
                </div>
            </div>
        </div>
    </div>
</header><!--头部-->
</body>
</html>

ju/illustration/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>JUJU.com</title>

    <!-- Styles -->


    <!-- favicon and touch icons -->
    <link rel="shortcut icon" href="{% static "assets/images/favicon.png"%}" >

    <!-- Bootstrap -->
    <link href="{% static "plugins/font-awesome/css/font-awesome.min.css"%}" rel="stylesheet">
    <link href="{% static "plugins/slick/slick.css"%}" rel="stylesheet">
    <link href="{% static "plugins/slick-nav/slicknav.css"%}" rel="stylesheet">
    <link href="{% static "plugins/wow/animate.css"%}" rel="stylesheet">
    <link href="{% static "assets/css/bootstrap.css"%}" rel="stylesheet">
    <link href="{% static "assets/css/theme.css"%}" rel="stylesheet">

</head>
<body>
<div id="page-loader">
    <div class="loaders">
        <img src="{% static "assets/images/loader/3.gif"%}" alt="First Loader">
        <img src="{% static "assets/images/loader/4.gif"%}" alt="First Loader">
    </div>
</div>
<header id="site-header">
    {% include "header.html" %}
</header>
  <div class="main-slider-wrapper clearfix">

    <div id="main-slider">
        <div class="slide"><img src="{% static "assets/images/slider/1.jpg"%}" alt="Slide"></div>
        <div class="slide"><img src="{% static "assets/images/slider/2.jpg"%}" alt="Slide"></div>
        <div class="slide"><img src="{% static "assets/images/slider/3.jpg"%}" alt="Slide"></div>
        <div class="slide"><img src="{% static "assets/images/slider/4.jpg"%}" alt="Slide"></div>
    </div>
    <div id="slider-contents">
        <div class="container text-center">
            <div class="jumbotron">
                <h1>Find Your Dream House</h1>
                <div class="contents clearfix">
                    <p>我们提供全面的历史成交信息查询、房价变化记录，您可以根据您的需要 <br>
                        精确地查询信息、预测房价，满足您的购房、投资需求</p>
                </div>
                <!--<a class="btn btn-warning btn-lg btn-3d" data-hover="Our Services" href="#" role="button">Our Services</a>
                <a class="btn btn-default btn-border btn-lg" href="#" role="button">Get a Quote</a>-->
            </div>
        </div>
    </div>
</div>

<section id="home-property-for-rent-listing">
    <header class="section-header home-section-header text-center">
        <div class="container">
            <h2 class="wow slideInLeft">平台主要功能</h2>
        </div>
    </header>
    <div class="container">
        <div class="row">
      <div class="col-md-2 col-md-offset-1">
        <div class="media-object-default">
          <div class="media">
            <div class="media-left">
                <a href="{% url 'illustration:index'%}">
                <img class="img-responsive img-rounded" src="{% static "images/图表预测表.png"%}" alt="placeholder image">
                <h4 style="text-align: center;">图说数据</h4> </a></div>

            <!--<div id="func-contents1">
        <div class="container text-center">
                <h3>房源信息</h3>
        </div>
    </div>-->
            <!--<div class="media-body">
              <h4 class="media-heading">Heading 1</h4>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat, sequi, repudiandae tenetur et veniam labore debitis repellendus totam non incidunt hic esse!</div>-->
          </div>
        </div>
      </div>
      <div class="col-md-2 col-md-offset-2">
        <div class="media">
          <div class="media-left"> <a href="{% url 'illustration:price_predict'%}"> <img class="img-responsive img-rounded" src="{% static "images/智能.png"%}" alt="placeholder image">
          <h4 style="text-align: center;">房价预测</h4></a></div>
          <!--<div class="media-body">
            <h4 class="media-heading">Heading 2</h4>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, odit, consequuntur, quae, at tempore nostrum perferendis corporis nam maxime tenetur iure facilis.</div>-->
        </div>
      </div>
      <div class="col-md-2 col-md-offset-2">
        <div class="media">
              <div class="media-left"> <a href="{% url 'illustration:invest_ass'%}"> <img class="img-responsive img-rounded" src="{% static "images/资讯.png"%}" alt="placeholder image">
              <h4 style="text-align: center;">投资助手</h4></a></div>
      <!--<div class="media-body">
            <h4 class="media-heading">Heading 3</h4>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, id, aut, officiis laboriosam a vero illo dolor asperiores provident quibusdam praesentium ipsum!</div>-->
        </div>
	  </div>
     </div>
   </div>
   </section>



<section id="home-features-section" class="text-center">
    <header class="section-header home-section-header">
       <div class="container">
           <h2 class="wow slideInRight">最新资讯</h2>
           <p class="wow slideInLeft"><a href="{% url 'illustration:news'%}
          ">查看更多</a></p>
       </div>
    </header>
    {% for news in newslist %}
        <div class="widget-post">
            <div class="row">
                <div>
                    <p class="entry-title",sytle="text-align:center"><a href="{{ news.link }}" target="_blank">{{ news.title }}</a></p>
                </div>
            </div>
        </div>
    {% endfor %}
	</section>

<footer id="footer">
<div class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <section class="widget about-widget clearfix">
                    <h4 class="title hide">About Us</h4>
                    <a class="footer-logo" href="#"><img src="{% static "assets/images/footer-logo.png" %}" alt="Footer Logo"></a>
                    <p>我们提供全面的历史成交信息查询、房价变化记录，您可以根据您的需要精确地查询信息、预测房价，满足您的购房、投资需求</p>
                    <ul class="social-icons clearfix">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                    </ul>
                </section>
            </div>
            <div class="col-md-4 col-sm-6">
                <section class="widget twitter-widget clearfix">
                    <h4 class="title"></h4>
                    <div id="twitter-feeds" class="clearfix"></div>
                </section>
            </div>
            <div class="col-md-4 col-sm-6">
                <section class="widget address-widget clearfix">
                    <h4 class="title">平台支持中心</h4>
                    <ul>
                        <li><i class="fa fa-map-marker"></i> 上海市，杨浦区，国定路777号</li>
                        <li><i class="fa fa-phone"></i>13167227669</li>
						<li><i class="fa fa-envelope"></i>1098912568@qq.com</li>
                        <li><i class="fa fa-clock-o"></i> 工作时间看心情</li>
                    </ul>
                </section>
            </div>
        </div>
    </div>
</div>
    <div class="site-footer-bottom">
        <div class="container">
          <p class="copyright pull-left wow slideInRight">© 2018 Designed by <a href="#">The Expendables</a>. All rights reserved.</p>
        </div>
    </div>
</footer>
<a href="#top" id="scroll-top"><i class="fa fa-angle-up"></i></a>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static "assets/js/jquery.min.js"%}"></script>
<script src="{% static "assets/js/bootstrap.min.js"%}"></script>
<script src="{% static "plugins/slick-nav/jquery.slicknav.min.js"%}"></script>
<script src="{% static "plugins/slick/slick.min.js"%}"></script>
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js"%}"></script>
<script src="{% static "plugins/tweetie/tweetie.js"%}"></script>
<script src="{% static "plugins/forms/jquery.form.min.js"%}"></script>
<script src="{% static "plugins/forms/jquery.validate.min.js"%}"></script>
<script src="{% static "plugins/modernizr/modernizr.custom.js"%}"></script>
<script src="{% static "plugins/wow/wow.min.js"%}"></script>
<script src="{% static "plugins/zoom/zoom.js"%}"></script>
<script src="{% static "plugins/mixitup/mixitup.min.js"%}"></script>
<script src="{% static "assets/js/theme.js"%}"></script>
</body>
</html>

ju/illustration/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JUJU.com</title>
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/index.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
     <link href={% static "assets/css/theme.css"%} rel="stylesheet">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	 <link rel="stylesheet" href="{% static "css/common.css" %}">
</head>
<body>
{% include "header.html" %}
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12 main">
                <div class="col-md-12"id="bg_img">
                    <div class="col-md-12"id="cover"></div>
                    <div class="col-md-3 col-md-offset-4"style="z-index: 2">

                    <div class="login-panel panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="{% url 'illustration:register'%}" role="form"method="post">
                                    <!-- 错误提示栏,可提示用户名已注册/用户名或密码不合法/两次密码输入不一致的错误 -->
                                    <div style="text-align: left; border: none; color: red; padding-bottom: 10px">
                                    {% for key, error in register_form.errors.items %}
                                    {{ error }}
                                    {% endfor %}
                                    {{ msg }}</div>
                                    <!-- 注册基本信息填写 -->
                                    <div class="form-group">
                                        <input name="username" type="text" class="form-control" placeholder="用户名（长度超过3位，含有a-z,0-9）">
                                    </div>
                                    <div class="form-group">
                                        <input name="password" type="password" class="form-control"placeholder="密码（长度不少于6位）">
                                    </div>
                                    <div class="form-group">
                                        <input name="repeat" type="password" class="form-control"placeholder="确认密码">
                                    </div>
                                    <input  class="btn btn-primary btn-block" type="submit" value="注册"/>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
<script src="{% static "assets/js/jquery.min.js"%}"></script>
<script src="{% static "assets/js/theme.js"%}"></script>

ju/illustration/templates/sidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul class="nav navbar-side">
                    <li id="communitybar"><a data-toggle="collapse" data-target="#collapseList1">查找小区
                        <span class="glyphicon glyphicon-chevron-down right" style="float:right;"></span></a>
                        <ul class="nav navbar-side collapse" id="collapseList1">
                            <li id="bizcircle_community"><a href="{% url 'illustration:search_community'  'bizcircle'%}">商圈周边小区</a></li>
                            <li id="subway_community"><a href="{% url 'illustration:search_community' 'subway'%}">地铁周边小区</a></li>
                        </ul>
                    </li>
                    <li id="sellinfobar"><a data-toggle="collapse" data-target="#collapseList2">历史成交信息
                    <span class="glyphicon glyphicon-chevron-down right"style="float:right;"></span></a>
                        <ul class="nav navbar-side collapse" id="collapseList2">
                            <li id="bizcircle_community"><a href="{% url 'illustration:his_price'%}">成交房价分析</a></li>
                            <li id="subway_community"><a href="{% url 'illustration:his_detail'%}">成交房源分析</a></li>
                        </ul>
                    </li>
                    <li id="rentinfo"><a href="..\community_info">小区详细信息</a></li>
    </ul>
</body>
</html>